name: collect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.7.1
  uuid:
  easy_stepper: ^1.2.0
  fl_chart: ^1.2.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  device_info_plus: ^13.2.0
  device_preview: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  encrypt: ^5.0.3
  flutter_secure_storage: ^11.1.0
  cryptography: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # app icon
    - assets/images/icon.png

    #onboarding
    - assets/images/on_boarding/onboarding1.png
    - assets/images/on_boarding/onboarding2.png
    - assets/images/on_boarding/onboarding3.jpg

    #authentication
    - assets/images/auth/google.png
    - assets/images/debtors/avatar.png


    #debts
    - assets/images/debts/whatsapp.png
    - assets/images/debts/call.png

    #installments
    - assets/images/installments/paying_methods.jfif
    - assets/images/installments/settle.jfif

    #no
    - assets/images/no/calender.png
    - assets/images/no/no_changes.png
    - assets/images/no/no_delays.png
    - assets/images/no/no_internet.png
    - assets/images/no/wallet.png
    - assets/images/no/no_debts.png
    - assets/images/no/no_debtors.png
    - assets/images/no/no_installments.png

    #countries flags
    - assets/images/countries/china.png
    - assets/images/countries/egypt.png
    - assets/images/countries/france.png
    - assets/images/countries/germany.png
    - assets/images/countries/italy.png
    - assets/images/countries/japan.png
    - assets/images/countries/spain.png
    - assets/images/countries/uk.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
