name: Build iOS Version For Appetize

on:
  workflow_dispatch:

jobs:
  build-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS Simulator
        run: flutter build ios --simulator --debug

      - name: Zip Simulator App
        run: |
          cd build/ios/iphonesimulator
          zip -r FlutterAppSimulator.zip Runner.app

      - name: Upload Simulator Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator
          path: build/ios/iphonesimulator/FlutterAppSimulator.zip